### ISSUE TITLE
Stream ended problem - V9

### ISSUE THREAD

**Issue by kaanduzbastilar** [fgl27/smarttv-twitch#250] opened 2022-11-18 15:31 UTC
Here is the console log, i can see streams but can not watch them, looks like i cannot connect to api servers.
<img width="1512" alt="Ekran Resmi 2022-11-18 18 26 53" src="https://user-images.githubusercontent.com/70735387/202740766-39ed2ed9-1875-49af-af43-fd625c40371e.png">

**Comment by fgl27** [comment] 2022-11-18 17:48
You need to use the release to install the app.

The release will download the missing private keys in runtime.

Do you have a issue using the release?

**Comment by NITROXIDAN** [comment] 2022-11-18 17:57
I installed both of them, same problem with release; i can see all streamers everything working but i can not watch them, it gives " * Live has ended exiting in 3 sec".

**Comment by fgl27** [comment] 2022-11-20 17:31
Probably DNS or network related issue.

**Comment by NITROXIDAN** [comment] 2022-11-20 17:43
I tried 3 different dns on tv.

**Comment by fgl27** [comment] 2022-11-20 17:58
Revise what is blocking the stream access something on yours network is

**Comment by DeneXX1** [comment] 2022-11-22 13:24
Got the Same Problem since today

**Comment by Nabite** [comment] 2022-11-22 14:45
Same problem for me started yesterday

**Comment by fgl27** [comment] 2022-11-22 20:02
The app fully works for me. Doesn't seems to be an twitch thing.

**Comment by DeneXX1** [comment] 2022-11-23 10:26
> The app fully works for me. Doesn't seems to be an twitch thing.

**Comment by DeneXX1** [comment] 2022-11-23 10:28
> The app fully works for me. Doesn't seems to be an twitch thing.

https://mega.nz/file/BYBEgYBC#pppw7_RVdrndg9bi5MUHngX7vTmig-t8X93KI3I_6-4



Pls fix

**Comment by fgl27** [comment] 2022-11-23 14:54
> > The app fully works for me. Doesn't seems to be an twitch thing.
> 
> https://mega.nz/file/BYBEgYBC#pppw7_RVdrndg9bi5MUHngX7vTmig-t8X93KI3I_6-4
> 
> Pls fix

Fix what?

https://imgur.com/a/qV3WXd6

Works means that is working.

I can't fix what is not there to me too fix.

**Comment by DeneXX1** [comment] 2022-11-23 14:57
Can you Check it for us with our Logs or Something Like that? Its Happen
for sone other People too

Felipe Leon ***@***.***> schrieb am Mi., 23. Nov. 2022, 15:55:

**Comment by fgl27** [comment] 2022-11-23 15:16
Yes just share the logs

**Comment by DeneXX1** [comment] 2022-11-23 15:17
Where i can find it? Can you tell me

Felipe Leon ***@***.***> schrieb am Mi., 23. Nov. 2022, 16:17:

**Comment by walkintall15** [comment] 2022-11-23 19:50
> The app fully works for me. Doesn't seems to be an twitch thing.

No idea what it is so far. I only know it stopped working for me a day or 2 ago. On the network/dns assumption. I have the Android branch on a Android tablet and a smartphone, and both are working flawless still. Tho not sure if its the network either. Unless the android branch is totally different. I tried different DNS's already, not found a fix yet.

Going to keep posting. If someone found a solution please post it. 

I am EU (Germany). Will probably trying to figure out how to connect the TV to a foreign VPN, to figure out if its the geo block/network issues.

I got an older Samsung, but other than that the version is the same as you. (Tizen 2.5)

**Comment by pnrxtx** [comment] 2022-11-24 16:47
I don't know how to do logs on tv.
Can confirm streams not starting. No network changes was made prior this.
tizen 2.3
https://imgur.com/a/0d4LrS5

**Comment by fgl27** [comment] 2022-11-24 21:23
I'm busy during week days, I'll help more in weekend.

But this issue is on the device and or network.

Probably not fixable as isn't an app issue.

**Comment by DeneXX1** [comment] 2022-11-24 21:31
A little tip: I think everyone with the problem here is from Germany

Felipe Leon ***@***.***> schrieb am Do., 24. Nov. 2022, 22:24:

**Comment by NITROXIDAN** [comment] 2022-11-24 22:22
I'm in Turkey, we need to be connecting from the same server.

**Comment by DeneXX1** [comment] 2022-11-26 15:10
Still the same Problem, any Updates?

**Comment by NITROXIDAN** [comment] 2022-11-27 12:23
I fixed my problem by buying xiaomi 4k stick :D

**Comment by fgl27** [comment] 2022-11-27 18:01
To install the app in debug mode... with is a similar process as you did in here https://github.com/fgl27/smarttv-twitch#install-the-application

But now you click on "Debug as" see on the below image

![image](https://user-images.githubusercontent.com/13755892/204152037-f9dd2afa-a868-4f3f-bcd3-ff03ffff5b2c.png)

When it finishes installing will open on the computer a window from the default browser click on the console tab as on bellow image, wait at least 60 seconds before taking the screenshot

![image](https://user-images.githubusercontent.com/13755892/204152042-53c7458b-3e39-4ab6-9880-02343a100a0b.png)

**Comment by fgl27** [comment] 2022-11-27 18:03
Anyone that shares the logs, just install the release app and do the above, also share a screen shot the about of the app plus your country.

make sure to open a few live stream to catch more then one errro.

Any doubt let me know

**Comment by fgl27** [comment] 2022-11-27 18:05
> I fixed my problem by buying xiaomi 4k stick :D

if the app works on the same network on an android device but not on TV points to a issue on the TV, related to how the app access the network, as both app work on the same way (access the same links).

maybe fixable maybe not all that can share some logs.

**Comment by pnrxtx** [comment] 2022-11-27 20:07
![1](https://user-images.githubusercontent.com/88897538/204157135-c352ee0a-f678-4845-92d9-acde8d6ffaaa.png)
![2](https://user-images.githubusercontent.com/88897538/204157140-8168c18b-0e8a-413a-a552-3e389934039d.png)
![IMG20221127220046](https://user-images.githubusercontent.com/88897538/204157229-706ec49d-5834-4b26-bcf8-03ae036bee72.jpg)

from Latvia

**Comment by baldisos** [comment] 2022-11-27 20:44
I have the same problem. But i have 3 devices and may have found something in relation to the others with the same problem.
All 3 devices are in the same network with the same nameserver settings etc.

It's working on Tizen 3.0 and 2.4 but not on Tizen 2.3.
Could be something with the Tizen version? The other screenshots of @pnrxtx show Tizen 2.3 too.

One of the 2 devices that's working:
![working](https://user-images.githubusercontent.com/76702976/204158550-8b7bf658-4b42-4195-9f7d-b265d93d30e8.jpg)

The device that's not working:
![not_working](https://user-images.githubusercontent.com/76702976/204158564-85a08c90-7ffb-487e-9a40-f63bf153c45a.jpg)

**Comment by fgl27** [comment] 2022-11-28 12:47
this is a device issues, noting that can do.

Samsung is enforcing Cross-domain, with prevents access from the device to Twitch server that provides the stream ulrs.

Noting that can be done, you must await the day Samsung desabe that.

**Comment by pnrxtx** [comment] 2022-11-29 03:44
Proxy didn't fix it.

**Comment by fgl27** [comment] 2022-11-29 12:54
Proxy may be out of service too many using it comes and goes, or not work for the same Cross-domain reason affecting twitch url.

**Comment by baldisos** [comment] 2022-11-29 17:49
If this is a cross-domain Problem, why would this only affect older devices? I have two devices that are newer, one of them only a few month, and they don't show these Problems? Wouldn't make sense for Samsung to update older devices first, i think the problem is elsewhere.

**Comment by fgl27** [comment] 2022-11-29 19:41
> If this is a cross-domain Problem, why would this only affect older devices? I have two devices that are newer, one of them only a few month, and they don't show these Problems? Wouldn't make sense for Samsung to update older devices first, i think the problem is elsewhere.

Where?

**Comment by georgebvro** [comment] 2022-11-30 06:37
I have the same problem, Live streams and videos (VODs) don't work.

But, Clips work.

If anyone knows the difference between how Live streams and videos are accessed, and how Clips are accessed, maybe we can find where the problem resides.

My device:
Samsung 40JU7000
Tizen 2.3

**Comment by baldisos** [comment] 2022-11-30 06:42
> > If this is a cross-domain Problem, why would this only affect older devices? I have two devices that are newer, one of them only a few month, and they don't show these Problems? Wouldn't make sense for Samsung to update older devices first, i think the problem is elsewhere.
> 
> Where?

I don't know yet. TLS maybe? The error says the Handshake fails. Looks like certificate issues.

**Comment by fgl27** [comment] 2022-11-30 13:34
> TLS maybe

maybes don't help.

this is related to Cross, Samsung probably update the version of they browser implementation and enable it across all site including the localhost on with is where this app runs.

Twitch doesn't accept any request from any site that isn't they if Cross is enable.

Is that simple there is no fix, or Samsung disable it or someone need to provide a solution as a proxy or something that can bypass the connection.

**Comment by georgebvro** [comment] 2022-11-30 15:31
> I have the same problem, Live streams and videos (VODs) don't work.
> 
> But, Clips work.
> 
> If anyone knows the difference between how Live streams and videos are accessed, and how Clips are accessed, maybe we can find where the problem resides.
> 
> My device: Samsung 40JU7000 Tizen 2.3

Anyone has an idea why Clips work while Live streams and Videos do not?

Another bit of information: The software version on the TV is 1570, not changed for about 16 months.

**Comment by baldisos** [comment] 2022-11-30 17:08
> > TLS maybe
> 
> maybes don't help.
> 
> this is related to Cross, Samsung probably update the version of they browser implementation and enable Cross to all site including the **localhost** which is where this app runs.
> 
> Twitch doesn't accept request from any site that isn't theirs if Cross is enabled.
> 
> Is that simple there is no fix, or Samsung disables it or someone needs to provide a solution as a proxy or something that can bypass the connection.

Doesn't make sense that Samsungs updates a Device that's 7 years old, while not updating the devices that are less than 2 years old. But anyway, i'm using Kodi now.

**Comment by fgl27** [comment] 2022-11-30 18:24
> > > TLS maybe
> > 
> > 
> > maybes don't help.
> > this is related to Cross, Samsung probably update the version of they browser implementation and enable Cross to all site including the **localhost** which is where this app runs.
> > Twitch doesn't accept request from any site that isn't theirs if Cross is enabled.
> > Is that simple there is no fix, or Samsung disables it or someone needs to provide a solution as a proxy or something that can bypass the connection.
> 
> Doesn't make sense that Samsung updates a Device that's 7 years old, while not updating the devices that are less than 2 years old. But anyway, i'm using Kodi now for that Device, this solves the Problem for me.

you don't get the point, they update they all, on this device they commit the mistake of enable cross for all sites.

that is it.

is very simple or they made a mistake or they decide that on this old device now it will be enabled, maybe is even a region thing, after all this is a security restriction.

**Comment by fgl27** [comment] 2022-11-30 18:25
> Anyone has an idea why Clips work while Live streams and Videos do not?

not the same thing, one has restriction other doesn't.

**Comment by baldisos** [comment] 2022-11-30 18:40
> > > > TLS maybe
> > > 
> > > 
> > > maybes don't help.
> > > this is related to Cross, Samsung probably update the version of they browser implementation and enable Cross to all site including the **localhost** which is where this app runs.
> > > Twitch doesn't accept request from any site that isn't theirs if Cross is enabled.
> > > Is that simple there is no fix, or Samsung disables it or someone needs to provide a solution as a proxy or something that can bypass the connection.
> > 
> > 
> > Doesn't make sense that Samsung updates a Device that's 7 years old, while not updating the devices that are less than 2 years old. But anyway, i'm using Kodi now for that Device, this solves the Problem for me.
> 
> you don't get the point, they update they all, on this device they commit the mistake of enable cross for all sites.
> 
> that is it.
> 
> is very simple or they made a mistake or they decide that on this old device now it will be enabled, maybe is even a region thing, after all this is a security restriction.

Point is, the last time that device was updated, was in July 2021.

**Comment by fgl27** [comment] 2022-11-30 20:09
This isn't a firmware thing, is just like any app can be updated without you even notice.

**Comment by Thebest35** [comment] 2022-12-01 01:47
Having the same issue in Germany. But as ive just read, there is a new official twitch app for Samsung TVs since this year's summer. But on my TV I can't find it. Does anyone know how to update the app list, so that twitch appears for installing? I can't even find it over search. Or ist only for new Samsung TVs with gaming hub?

**Comment by Thebest35** [comment] 2022-12-01 01:58
I have just seen there are some new apps to install but not the twitch app.. And others could install on old Samsung tvs.. I don't get it.. If someone finds a way to install official twitch version even if it's not to find on the TV pls let me know

**Comment by fgl27** [comment] 2022-12-01 22:29
no span please

**Comment by georgebvro** [comment] 2022-12-02 15:59
Suddenly, Live streams and Videos are working again. Maybe someone else can check as well.

Don't close the issue just yet, I think when it stopped working about 2 weeks ago, it worked after a day or two and then broke again.

Let's test it for a few of days.

**Comment by pnrxtx** [comment] 2022-12-02 18:33
Yes, works from today for some reason.

**Comment by Thebest35** [comment] 2022-12-02 18:58
i dont get why u marked my posts as spam and deleted it.. they were helping.. but now its working for me again too.. i have written with samsung support yesterday. they were really interested and i even showed them the link of this thread. maybe this made them repair it.

**Closed** 2022-12-02 19:05 UTC
Labels: bug, help wanted, Device bug, Need more info, Tizen and or device issue
