### ISSUE TITLE
Can not open stream in 2160p60

### ISSUE THREAD

**Issue by amDude1848** [fgl27/smarttv-twitch#180] opened 2021-05-25 17:37 UTC
I tried open a stream which is in a resolution of 2160p60. https://www.twitch.tv/pcdocberlin

The App tried to open it, but unfortunatly it did not work out. I use a 7-Series Samsung-TV which supports 4k actually.

Thanks in preview and for your great work. 
amDude

**Comment by fgl27** [comment] 2021-05-25 17:58
Yours TV issue my works well and ia a old TV

![IMG_20210525_145325962_HDR](https://user-images.githubusercontent.com/13755892/119545767-8f666400-bd69-11eb-80bd-4271dd16cacf.jpg)

If you wanna to debug the issue, install the app in debug here is how to debug https://github.com/fgl27/smarttv-twitch/issues/104#issuecomment-610563192

Share the console window after trying to play that stream a few times

**Comment by amDude1848** [comment] 2021-05-25 20:17
Thanks a lor your care. I succesfully installed the debug.App on my TV, but i can't open any stream with it. When i start a stream itt says "stream ended in 3...2..1.." no matter in which resoulution, even when the stream is online.

The console at Chrome (Ubuntu) opens, but it don't show anything, just a blank document.

**Comment by fgl27** [comment] 2021-05-25 23:12
You need to instal the release the same app that you have workin, not that one from that post that is very old.
Sorry to not make that clear

**Comment by fgl27** [comment] 2021-05-25 23:16
THe steps to debug are, use the release zip download from this step of the main page https://github.com/fgl27/smarttv-twitch#setup-the-application

But do not install it in debug mode

![image](https://user-images.githubusercontent.com/13755892/78708031-da17e900-78e7-11ea-8715-f0e587ca447e.png)

After the installation finished you need to press OK on the TV remote, and a browser window will open on the PC

![image](https://user-images.githubusercontent.com/13755892/78708106-f74cb780-78e7-11ea-9276-0e6f526d61a8.png)

On the computer select `console` tab, as in the image above, then use the app in the requested way to produce the logs.

**Comment by amDude1848** [comment] 2021-05-26 01:48
Thats okay and sorry, took a bit longer. I broke Tizen-SDK completely by updating it and i had to re-install it on a fresh Ubuntu-Virtual Machine..

Now when i try to send the Twitch-App to my TV - i get the error that the password in Java-SDK is wrong. I could fix it in the past, when i installed Twitch-App a few month ago, but this fix is not working now.

![Bildschirmfoto vom 2021-05-26 03-43-52](https://user-images.githubusercontent.com/84803655/119590376-f66d3280-bdd4-11eb-9285-4405e8c27d43.png)

**Comment by fgl27** [comment] 2021-05-26 01:57
I think you have to set a password for the user on Ubuntu... Use the command **passwd** in terminal, then when you try to install tizen will ask for it...

At least here is how I do, before it install it prompt me for my password

**Comment by amDude1848** [comment] 2021-05-26 02:06
Thank you, i tried it out, but it's not working. Tizen is not asking me for a password while install. It brakes up with this message at around 56%.

**Comment by amDude1848** [comment] 2021-05-26 02:17
After Reboot it's asking for a Password, but it says it is wrong, which is not possible. If i try out a wrong pw for testing it is re-asking and if i write the correct password it shows the above window with Java SDK.

**Comment by fgl27** [comment] 2021-05-26 19:57
I have no idea, on my computer it just works, and I'm using Ubuntu.

I'll let this open, if you manage to be able to debug let me know, that channel seems to keep they VOD on the site for some time the latest are all in 4k we can use that on a future test.

**Comment by alchemistake** [comment] 2021-06-04 13:38
can it be resolved by editing widget.info?

**Comment by amDude1848** [comment] 2021-08-01 21:43
I have edited widget.info to my TV-Resolution 3840x2160 and resaved the App on my TV, but that did not worked out for the problem.

**Comment by amDude1848** [comment] 2021-09-04 14:22
I am not sure about the reason, but 2160p and 1440p with 30 fps seems like work excellent now. Unfortunately i can't find a stream or a video with 2160 and 60 fps for checking out, but i will report back when i find one.

**Comment by fgl27** [comment] 2021-09-04 14:30
PCDocBerlin has vods in 2160p and 60 fps

**Comment by amDude1848** [comment] 2021-09-04 14:36
I am sorry, i did not find them directly, but i got them now. Unfortunatelly they are not working in 60 fps. Only 30 fps videos in high resolution are working here. I use the latest version of Twitch-App.

**Comment by fgl27** [comment] 2021-09-04 14:49
That is fine, the issue is probably related to the tv codec implementation regarding the resolution.

from PCDocBerlin vods technical the 1440p and 2160p seem to use the same codec but the resolution change causes the issue.

![Screenshot from 2021-09-04 11-46-29](https://user-images.githubusercontent.com/13755892/132098558-547b6345-ac6e-48cb-9185-0de38d1e867f.png)

**Comment by amDude1848** [comment] 2021-09-04 14:53
So far i understood. Looks like i can not do something on my TV to fix it. I am so sorry i can't send an error-protocol from the Debug-Version - i tried 3 browsers, but i only get a blank site. :-(

**Comment by fgl27** [comment] 2021-09-04 15:00
if someday that improve let us know.

**Comment by amDude1848** [comment] 2021-09-04 15:01
Okay

**Comment by ancho85** [comment] 2022-01-11 04:17
> Yours TV issue my works well and is a older serie 6 4K TV
> 
> ![IMG_20210525_145325962_HDR](https://user-images.githubusercontent.com/13755892/119545767-8f666400-bd69-11eb-80bd-4271dd16cacf.jpg)
> 
> If you wanna to debug the issue, install the app in debug here is how to debug [#104 (comment)](https://github.com/fgl27/smarttv-twitch/issues/104#issuecomment-610563192)
> 
> Share the console window after trying to play that stream a few times

How can be enabled a more verbose logging? Main_isReleased is checked to show more information but I cannot see in the logs that info

**Comment by fgl27** [comment] 2022-01-12 00:13
The release only shows log that are errors.

Main_isReleased need to be disabled to show all player logs.

I can add a settings option to enable all player logs.

That doesn't help much as this specific problem is a TV problem I don't think can be resolved via ao e configuration.

Any way I let you know when the option in settings is ready.

**Comment by ancho85** [comment] 2022-01-12 00:23
That would be great. I'm seeing the logs but it stop when the player tries to load the m3u playlist generated by the service. If I use that playlist and save it to see with vlc in the computer it works (streams with different qualities) , but here apparently the TV fails to load them (or the player itself)

**Comment by fgl27** [comment] 2022-07-27 20:11
reopen if any news

**Closed by fgl27** 2022-07-27 20:11 UTC
Labels: Tizen and or device issue
