### ISSUE TITLE
Tizen Certificate Manager not working

### ISSUE THREAD

**Issue by Rossano95** [fgl27/smarttv-twitch#4] opened 2019-01-04 02:49 UTC
When I click finish at the end of the creation of the certificate the app just don't do anything. I tried to make another certificate with Samsung instead of Tizen and when I Run as > 1 Tizen wen Application I get a fail.

The TV is a UE50NU7090
Tizen Studio 3.0

**Comment by fgl27** [comment] 2019-01-04 03:47
I have created a certificate in the past, and works just as described in https://github.com/fgl27/smarttv-twitch#generate-a-certificate

But I tried to create a new and it's just like you wrote.

I also try this https://developer.samsung.com/galaxy-watch/develop/getting-certificates/create
And I was able to create one, in the past that type did not allow to install the app, but  selected and it allow me, so please try and report.

**Comment by Rossano95** [comment] 2019-01-04 11:38
I did everything. After I press run as I get a "Different Profile" alert. I click yes and the problem is the same.

This is the log:

Launching the Tizen application...
# If you want to see the detailed information,
# please set the logging level to DEBUG in Preferences and check the log file in 'C:\tizen-studio-data\ide\logs/ide-20190104_123042.log'.

[Initializing the launch environment...]
    RDS: Off
    Target information: UE50NU7090
    Application information: Id(qY6HyNzLIR.TwitchTv), Package Name(qY6HyNzLIR), Project Name(BasicUI)
[Transferring the package...]
    Transferred the package: wgt stream -> /home/owner/share/tmp/sdk_tools/tmp/BasicUI.wgt
[Installing the package...]
install qY6HyNzLIR.TwitchTv
package_path /home/owner/share/tmp/sdk_tools/tmp/BasicUI.wgt
was_install_app return WAS_TRUE
app_id[qY6HyNzLIR.TwitchTv] install start
app_id[qY6HyNzLIR.TwitchTv] installing[7]
app_id[qY6HyNzLIR.TwitchTv] installing[10]
app_id[qY6HyNzLIR.TwitchTv] installing[13]
app_id[qY6HyNzLIR.TwitchTv] installing[15]
app_id[qY6HyNzLIR.TwitchTv] installing[18]
app_id[qY6HyNzLIR.TwitchTv] installing[21]
app_id[qY6HyNzLIR.TwitchTv] installing[23]
app_id[qY6HyNzLIR.TwitchTv] install failed[118012]
spend time for wascmd is [1443]ms
cmd_ret:0
    An exception occurred
(Installing the package... > Fail)
An exception occurred
Unexpected stop progress...
(4.026 sec)

**Comment by fgl27** [comment] 2019-01-04 12:38
The problem is to create a normal certificate is to create a autor.
Try again to create a profile  using...

**back to Tizen Studio > Tools > Certificate Manager > + > select/click Tizen >** 

but on create a new author use "select existing..." because when you use https://developer.samsung.com/galaxy-watch/develop/getting-certificates/create you already created one

![screenshot from 2019-01-04 10-30-43](https://user-images.githubusercontent.com/13755892/50688354-3799f780-100c-11e9-9b4d-ea4df7029fe5.png)

Find this folder... I don't know where it is on windows machine

![screenshot from 2019-01-04 10-29-52](https://user-images.githubusercontent.com/13755892/50688384-57312000-100c-11e9-936d-cca3ccb92bff.png)

the folder to look for in linux has this name "SamsungCertificate" and inside must have the previously created certificated, and inside must have **author.p12** file chose that

![screenshot from 2019-01-04 10-29-57](https://user-images.githubusercontent.com/13755892/50688489-d0307780-100c-11e9-8a7a-88f50f7ac6de.png)

put yours password, and now you must be able to click on finish.

Use that just created certificated as default and let me know.

**Comment by Rossano95** [comment] 2019-01-04 13:07
Thank you. This worked

**Comment by fgl27** [comment] 2019-01-04 13:36
1080p must be available on the streams so you can use, some streams don't have that.

just check in twtch.tv for the stream and you will see that what is in the website is on the app.

if you see more resolution on the site then the app, tell me the stream so I can check.

**Comment by Rossano95** [comment] 2019-01-04 13:49
I see the resolution in the app. But when i click ok the stream starts buffering and goes back to 720.

**Comment by fgl27** [comment] 2019-01-04 13:51
what stream?
is yours internet enough?
because the app automatic changes the resolution when the internet is not enough.

**Comment by Rossano95** [comment] 2019-01-04 13:52
This is the stream: https://www.twitch.tv/goeasytwitch

I have 200mbps so I think it's enough. I can see it on my pc without any issues. Also on the original app for tizen. I installed this for the chat and the better interface.

**Comment by fgl27** [comment] 2019-01-04 13:56
1080p just fine to me, you must have some network problem there, the app will not change the resolution unless it can't open because internet related issue, you can try to use a cable in case you are in wifi or just a simple reboot of the tv by removing it from the wall.

**Comment by Rossano95** [comment] 2019-01-04 14:03
Now I am using the cable. It seems that I can't watch 60fps contents. Also in 720. It's stange. I don't think that it's a connection issue. The internet is really fast.

**Comment by fgl27** [comment] 2019-01-04 14:05
all streams have that problem?

because no one ever had a problem like that.

**Comment by Rossano95** [comment] 2019-01-04 14:07
Yes, all of them. Is there a way to see if there is an error? Like a log or something like this. Maybe is the TV that has some incompatibilities?

**Comment by fgl27** [comment] 2019-01-04 14:20
video and clips also have the same resolution as the streams.

Do they also have this problem?

what happens when you press entre after select 1080p60, it start buffer and plays then buffer again, or it never plays? just keeps buffering until it loads the 720

**Comment by Rossano95** [comment] 2019-01-04 14:34
It's the same. I tried all the settings. It only takes longer to go back to 720. Only 720, not even 720 60 fps

**Comment by fgl27** [comment] 2019-01-04 14:39
are you shore you power off the TV, removing from the wall?

**Comment by Rossano95** [comment] 2019-01-04 14:44
I unplugged again. It's the same. But is there any log? So I can see if it's an error? Like codecs or something like that. The TV is pretty new and with the original app the streaming is working.

**Comment by Rossano95** [comment] 2019-01-04 14:54
This is the console log. I started a debug from tizen studio.

https://fgl27.github.io/smarttv-twitch/release/githubio/css/font-awesome.min.css Failed to load resource: net::ERR_NETWORK_CHANGED
https://fgl27.github.io/smarttv-twitch/release/githubio/css/master.css Failed to load resource: net::ERR_NETWORK_CHANGED
master.js:1 language is it_IT
master.js:1 InitScreens place holder
VM36:1 Entering setDisplayRect
VM36:1 adding listener
VM36:1 Entered AVPlayManager.prepareAsync()
webapis.min.js:1 [productinfo.js] isUDPanelSupported  begin
webapis.min.js:1 [productinfo.js] isUDPanelSupported  end [object Object]
webapis.min.js:1 [productinfo.js] isUDPanelSupported message data true
webapis.min.js:1 [productinfo.js] getFirmware  begin
webapis.min.js:1 [productinfo.js] getFirmware  end [object Object]
webapis.min.js:1 [productinfo.js] getFirmware message data T-KTSUDEUC-1007.1
webapis.min.js:1 [productinfo.js] getModel  begin
webapis.min.js:1 [productinfo.js] getModel  end [object Object]
webapis.min.js:1 [productinfo.js] getModel message data UNU7090
index.html:1 Failed to decode downloaded font: https://fgl27.github.io/smarttv-twitch/release/githubio/css/fonts/BabelStoneHan.woff
index.html:1 OTS parsing error: OS/2: Failed to read version 5-specific fields
webapis.min.js:1 [network.js] addNetworkStateChangeListener  success
webapis.min.js:1 [network.js] listenerId 0
webapis.min.js:1 [webapi.js] cbArr length: 1, then remove Callback!
VM36:1 adding listener
VM36:1 Entered AVPlayManager.prepareAsync()
master.js:1 Cannot read property 'setPreviewData' of undefined
jquery.min.js:2 GET https://api.betterttv.net/2/channels/faker 404 ()
send @ jquery.min.js:2
ajax @ jquery.min.js:2
p.(anonymous function) @ jquery.min.js:2
getJSON @ jquery.min.js:2
(anonymous) @ ?theme=bttv_blackchat&channel=faker&fade=false&bot_activity=true&prevent_clipping=false:434
loadEmotes @ ?theme=bttv_blackchat&channel=faker&fade=false&bot_activity=true&prevent_clipping=false:433
load @ ?theme=bttv_blackchat&channel=faker&fade=false&bot_activity=true&prevent_clipping=false:322
(anonymous) @ ?theme=bttv_blackchat&channel=faker&fade=false&bot_activity=true&prevent_clipping=false:637
k @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
D @ jquery.min.js:2
jquery.min.js:2 GET https://api.frankerfacez.com/v1/room/faker 404 ()
send @ jquery.min.js:2
ajax @ jquery.min.js:2
p.(anonymous function) @ jquery.min.js:2
getJSON @ jquery.min.js:2
(anonymous) @ ?theme=bttv_blackchat&channel=faker&fade=false&bot_activity=true&prevent_clipping=false:450
loadEmotes @ ?theme=bttv_blackchat&channel=faker&fade=false&bot_activity=true&prevent_clipping=false:449
load @ ?theme=bttv_blackchat&channel=faker&fade=false&bot_activity=true&prevent_clipping=false:322
(anonymous) @ ?theme=bttv_blackchat&channel=faker&fade=false&bot_activity=true&prevent_clipping=false:637
k @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
D @ jquery.min.js:2
VM36:1 adding listener
VM36:1 Entered AVPlayManager.prepareAsync()
VM26:1 ########## exception
(anonymous) @ VM26:1
VM26:1 DOMException: Failed to execute 'open' on 'Document': Can only call open() on same-origin documents.
(anonymous) @ VM26:1
VM36:1 adding listener
VM36:1 Entered AVPlayManager.prepareAsync()
VM26:1 ########## exception
(anonymous) @ VM26:1
VM26:1 DOMException: Failed to execute 'open' on 'Document': Can only call open() on same-origin documents.
(anonymous) @ VM26:1
VM36:1 adding listener
VM36:1 Entered AVPlayManager.prepareAsync()
VM26:1 ########## exception
(anonymous) @ VM26:1
VM26:1 DOMException: Failed to execute 'open' on 'Document': Can only call open() on same-origin documents.
(anonymous) @ VM26:1

**Comment by fgl27** [comment] 2019-01-04 14:56
what original app?

the player used here is the samsung default player, same used on original fork https://github.com/nikitakatchik/smarttv-twitch

yes you can log, but will only show a error if there is a error, with I doubt that will shows as errors causes crashes and this behavior is simple is just a timeout as took too long to open then the quality goes down.

To see the logs download the source https://codeload.github.com/fgl27/smarttv-twitch/zip/master
and install that making a new app in tizen, then when is time to install click on the lady bug icon (top left under file)

it will install the app in debug mode, it will open on the computer a window from the default browser click in console to see the logs

![screenshot from 2019-01-04 12-52-08](https://user-images.githubusercontent.com/13755892/50693933-a2086300-101f-11e9-8848-9597f1cd0358.png)

After the app finished load it will request you to press OK, then after you see the above screen you can press the B or green key, to force reload the app, it will make all the app show all initialization the logs then if see this

![screenshot from 2019-01-04 12-54-32](https://user-images.githubusercontent.com/13755892/50694021-e5fb6800-101f-11e9-88f5-0de9c23b9a43.png)

is because all the logs are be display, from that you can try to open some streams.

It will probably not log anything help full, but then I check where I can put extra logs so we can see where it is not working...

is a slow process unless you know how to code, as I can't simulate the problem here and I need to guess what to do on most situations and request you to test and test and test...

**Comment by Rossano95** [comment] 2019-01-04 15:04
This is the only error that I see:

Entered AVPlayManager.prepareAsync()
VM26:1 ########## exception
(anonymous) @ VM26:1
VM26:1 DOMException: Failed to execute 'open' on 'Document': Can only call open() on same-origin documents.

**Comment by fgl27** [comment] 2019-01-04 15:07
I need to see all the log, that means nothing to me.

I need to see where it happens se the log it show the lines of where it happens, that is way you need to install the source as above and log that the release can't be use for logging is not ready for it.

**Comment by Rossano95** [comment] 2019-01-04 15:13
This is the log:

Main.js:200 language is it_IT
Screens.js:6 InitScreens place holder
VM63:1 Entering setDisplayRect
VM63:1 adding listener
VM63:1 Entered AVPlayManager.prepareAsync()
webapis.min.js:1 [productinfo.js] isUDPanelSupported  begin
webapis.min.js:1 [productinfo.js] isUDPanelSupported  end [object Object]
webapis.min.js:1 [productinfo.js] isUDPanelSupported message data true
webapis.min.js:1 [productinfo.js] getFirmware  begin
webapis.min.js:1 [productinfo.js] getFirmware  end [object Object]
webapis.min.js:1 [productinfo.js] getFirmware message data T-KTSUDEUC-1007.1
webapis.min.js:1 [productinfo.js] getModel  begin
webapis.min.js:1 [productinfo.js] getModel  end [object Object]
webapis.min.js:1 [productinfo.js] getModel message data UNU7090
Main.js:732 Tizen Version: 4.0 | TV: UNU7090 | FW: T-KTSUDEUC-1007.1
index.html:1 Failed to decode downloaded font: https://fgl27.github.io/smarttv-twitch/release/githubio/css/fonts/BabelStoneHan.woff
index.html:1 OTS parsing error: OS/2: Failed to read version 5-specific fields
webapis.min.js:1 [network.js] addNetworkStateChangeListener  success
webapis.min.js:1 [network.js] listenerId 0
SmartHub.js:40 Cannot read property 'setPreviewData' of undefined
webapis.min.js:1 [webapi.js] cbArr length: 1, then remove Callback!
Play.js:634 Play_onPlayer: 

http://video-weaver.mil01.hls.ttvnw.net/v1/playlist/CrUDAASs3y12bue7uEVqLsB…XzLynFKa5SzTep2KdoymdBkp_ISEHxrYf40C-XX1Y5ku8yssb8aDMSuQRmdHkWUeLSMrA.m3u8

VM63:1 adding listener
VM63:1 Entered AVPlayManager.prepareAsync()
jquery.min.js:2 GET https://api.betterttv.net/2/channels/faker 404 ()
send @ jquery.min.js:2
ajax @ jquery.min.js:2
p.(anonymous function) @ jquery.min.js:2
getJSON @ jquery.min.js:2
(anonymous) @ ?theme=bttv_blackchat&channel=faker&fade=false&bot_activity=true&prevent_clipping=false:434
loadEmotes @ ?theme=bttv_blackchat&channel=faker&fade=false&bot_activity=true&prevent_clipping=false:433
load @ ?theme=bttv_blackchat&channel=faker&fade=false&bot_activity=true&prevent_clipping=false:322
(anonymous) @ ?theme=bttv_blackchat&channel=faker&fade=false&bot_activity=true&prevent_clipping=false:637
k @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
D @ jquery.min.js:2
jquery.min.js:2 GET https://api.frankerfacez.com/v1/room/faker 404 ()
send @ jquery.min.js:2
ajax @ jquery.min.js:2
p.(anonymous function) @ jquery.min.js:2
getJSON @ jquery.min.js:2
(anonymous) @ ?theme=bttv_blackchat&channel=faker&fade=false&bot_activity=true&prevent_clipping=false:450
loadEmotes @ ?theme=bttv_blackchat&channel=faker&fade=false&bot_activity=true&prevent_clipping=false:449
load @ ?theme=bttv_blackchat&channel=faker&fade=false&bot_activity=true&prevent_clipping=false:322
(anonymous) @ ?theme=bttv_blackchat&channel=faker&fade=false&bot_activity=true&prevent_clipping=false:637
k @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
D @ jquery.min.js:2
Play.js:634 Play_onPlayer: 

http://video-weaver.mil01.hls.ttvnw.net/v1/playlist/CrUDAASs3y12bue7uEVqLsB…XzLynFKa5SzTep2KdoymdBkp_ISEHxrYf40C-XX1Y5ku8yssb8aDMSuQRmdHkWUeLSMrA.m3u8

VM63:1 adding listener
VM63:1 Entered AVPlayManager.prepareAsync()
VM26:1 ########## exception
(anonymous) @ VM26:1
VM26:1 DOMException: Failed to execute 'open' on 'Document': Can only call open() on same-origin documents.
(anonymous) @ VM26:1
Play.js:634 Play_onPlayer: 

http://video-weaver.mil01.hls.ttvnw.net/v1/playlist/CrMDJ_7DBl0qyQ9bISdPR4g…VYK6HEud8X7dGGtTJ9MX58_GO5EhD28dSATvHgaoBgmpcSriLPGgwFC2ISrsd_ABUcU4A.m3u8

VM63:1 adding listener
VM63:1 Entered AVPlayManager.prepareAsync()
VM26:1 ########## exception
(anonymous) @ VM26:1
VM26:1 DOMException: Failed to execute 'open' on 'Document': Can only call open() on same-origin documents.
(anonymous) @ VM26:1
Play.js:634 Play_onPlayer: 

http://video-weaver.mil01.hls.ttvnw.net/v1/playlist/CrMD8AuZKp19q-hExO6XL6X…5klNtRQRSrMncT2aNrAiq6damFEhAi7-7yjGujuSebYeCwStDlGgz-OhBQzpaIFUF7OpU.m3u8

VM63:1 adding listener
VM63:1 Entered AVPlayManager.prepareAsync()
VM26:1 ########## exception
(anonymous) @ VM26:1
VM26:1 DOMException: Failed to execute 'open' on 'Document': Can only call open() on same-origin documents.
(anonymous) @ VM26:1

**Comment by fgl27** [comment] 2019-01-04 15:56
download the source https://codeload.github.com/fgl27/smarttv-twitch/zip/master again extract and replace the folder /app/specific from the folder where you have the tizen app

**Comment by Rossano95** [comment] 2019-01-04 18:00
Now it's working. I don't know. I had to reinstall twice because the first time the chat didn't work. It's possible that there's a problem with Tizen Studio 3.0? Thank you for your help. If you find the cause let me know.

**Comment by fgl27** [comment] 2019-01-04 18:01
What work?
the one instaled from release of the one instaled from the source aka this link https://codeload.github.com/fgl27/smarttv-twitch/zip/master?

if is the one from this link https://codeload.github.com/fgl27/smarttv-twitch/zip/master

try a 1080p video

**Comment by Rossano95** [comment] 2019-01-04 18:13
This works: https://codeload.github.com/fgl27/smarttv-twitch/zip/master
Now the only thing that is not working is the user. When I put my username it becomes testtwitch27.

**Comment by fgl27** [comment] 2019-01-04 18:16
yes that is a test app not supposed to be used, you need to use the release.

is video 1080p working or not so I can update the release?

**Comment by Rossano95** [comment] 2019-01-04 18:17
Yes. It's working. I tested also clips and videos. Thank you.

**Comment by fgl27** [comment] 2019-01-04 18:17
I let you know when you can try the release. in a few minutes...

**Comment by Rossano95** [comment] 2019-01-04 18:22
Ok, thank you

**Comment by fgl27** [comment] 2019-01-04 18:50
OKtry the released, that version auto update it self to check if did open the about, Red or A key then about and APP version must be 4.0.1.010419-01

the try 1080p60 live/videos/clips and tell me the result
if all OK I explain the issue and close.

**Comment by Rossano95** [comment] 2019-01-04 19:15
Now it's all working. The version is the right one. Thank you.

**Comment by fgl27** [comment] 2019-01-04 19:20
:+1: 

The samsung support for 4k content is enable
https://developer.samsung.com/tv/develop/guides/multimedia/4k-uhd-video

For some reason on my TV it just work OK, on yours it crashes on 60fps as you showed.
Technically it doesn't supports H.264 60 fps as described there.

But way doesn't crash on all TV? (rhetorical)

This TV OS is really bad, as twitch doesn't have 4k content, I will keep this disable, until the day we can evaluated the codec used by twitch in relation to the supported one.

**Comment by Rossano95** [comment] 2019-01-04 19:24
Thank you, so now it's 60fps or not?

**Comment by fgl27** [comment] 2019-01-04 19:36
it's

**Comment by Rossano95** [comment] 2019-01-04 19:44
Ok. So just to understand. The codec doesn't support 60 fps but it works anyway?

**Comment by fgl27** [comment] 2019-01-04 20:22
not what I was toking about.
I share the link for the 4k support video playback of the TV
https://developer.samsung.com/tv/develop/guides/multimedia/4k-uhd-video

with only support 60 fps if the codec is HEVC (H.265) but twithc is using H.264 BP/MP/HP for all content 60 or 30 fps doesnot matter the resoluciton

With that 4k support enable it crashes on yours TV trying to play H.264 BP/MP/HP 60 fps as the max fps of that codec when 4k is enable is 24, disabling the 4k support all OK

the content from twitch is not in 4k anyway so way keep it enable?

the day twitch enable full 4k support I recheck this featuring. will play even disable but may have some improve when enable for a supported codec

**Comment by Rossano95** [comment] 2019-01-04 22:05
Ok, I understood. Thank you. I am translating the app in Italian. When I think it's ready I will send it to you. Can you insert the translation even if it's not complete or perfect?

**Comment by Rossano95** [comment] 2019-01-04 22:13
This is translated in Italian. But when I try to test the app I get an error, maybe I touched something that I had not to:
[flbtxFhd64] app/languages/en_US.js:125: Uncaught SyntaxError: Unexpected identifier
[flbtxFhd64] app/specific/Main.js:186: Uncaught ReferenceError: en_USLang is not defined

[en_US.zip](https://github.com/fgl27/smarttv-twitch/files/2728736/en_US.zip)

**Comment by Rossano95** [comment] 2019-01-05 12:18
Now it should be pretty much OK. The only way to check everything is to use the app. Maybe someone will notice an error and wil tell us. Tell me when I can try the language on the release version. Thank you for your time.
[it_IT.zip](https://github.com/fgl27/smarttv-twitch/files/2729477/it_IT.zip)

**Comment by fgl27** [comment] 2019-01-05 13:01
OK thanks.

I'll check and push later today, I let you know here.

**Comment by fgl27** [comment] 2019-01-05 13:38
The language is on release, test and let me know if any adjustment is needed.

**Comment by Rossano95** [comment] 2019-01-05 14:09
Perfect. I think that it's pretty good. Can you explain me how the smart hub preview for the first user works?
I don't see the contents when on the app.

**Comment by fgl27** [comment] 2019-01-05 14:30
there is a key on the remote

![control](https://fgl27.github.io/smarttv-twitch/screenshot/controler.png)

call smart hub, it show the user content when pressed above the app icon on the app menu of the TV this
![Live](https://fgl27.github.io/smarttv-twitch/screenshot/smarthub.jpeg)

off course that image is only a random example, what show is yours user content.

**Comment by Rossano95** [comment] 2019-01-05 14:36
Ok. I don't see the content. I can see the contents on Netflix, Prime Video ecc.

**Comment by fgl27** [comment] 2019-01-05 14:50
I notice this already in tizen 4.0 before, but I can't test I don't have a TV, from yours log there is this

	SmartHub.js:40 Cannot read property 'setPreviewData' of undefined

the variable in't undefined works OK on my TV, I duno of way that happens, and because of that no preview is loaded.
I thinking on how to address this I let you know if I have something to test

**Comment by Rossano95** [comment] 2019-01-05 14:52
Ok, thank you. This is not a real issue. I just noticed that this didn't worked.

**Comment by fgl27** [comment] 2019-01-05 15:44
I add a simple change can you try?

Download the source https://codeload.github.com/fgl27/smarttv-twitch/zip/master

and on that debug test app you already have, replace the file **config.xml** and the folder **app**, install the app as debug place the app icon in the smarthub menu and tell me if you see the preview, try that before adding a user, wait one minute them  add a user and see what happen.

Share the result of the log here.

**Comment by Rossano95** [comment] 2019-01-05 15:59
Now the preview it's working. I can't add the user. It's the test user.

**Comment by Rossano95** [comment] 2019-01-05 16:30
Updated the translation. I forgot two words.
[it_IT.zip](https://github.com/fgl27/smarttv-twitch/files/2729659/it_IT.zip)

**Comment by fgl27** [comment] 2019-01-05 16:49
but have you added the test user?
can you add and see if the content is there.
because the error is there and when adding the user the preview must change and show all the content for the user

I don't think is working

**Comment by Rossano95** [comment] 2019-01-05 16:52
When I add the user I still have in the preview "Add User". Which user I have to add?

**Comment by fgl27** [comment] 2019-01-05 17:01
So it doesn't work at all.

**Comment by Rossano95** [comment] 2019-01-05 17:05
But now I can see something. Before I wasn't seeing anything. In the preview I see in this order:

Live, Add User, Featured, Games, Videos, Clips.

And is there a way to tranlate this?

**Comment by Rossano95** [comment] 2019-01-05 17:32
Ok, thank you

**Comment by Rossano95** [comment] 2019-01-05 17:36
This is what I see. The one with test in the logo is the one made from source. The other one is the release. Have you seen the updated traduction? 
[it_IT.zip](https://github.com/fgl27/smarttv-twitch/files/2729712/it_IT.zip)

![photo_2019-01-05_18-34-32](https://user-images.githubusercontent.com/35000827/50727248-98aef180-1118-11e9-9a54-7a188545c144.jpg)
![photo_2019-01-05_18-34-27](https://user-images.githubusercontent.com/35000827/50727249-98aef180-1118-11e9-871f-bd4e74c23d0b.jpg)

**Comment by fgl27** [comment] 2019-01-05 17:46
Yes I understand what is going on, I have all the info.

Already update the translation, you can see on the release version if you update it, by closing (via choosing close in the exit dialog or holding return key to force close it) and reopening the app.

**Comment by fgl27** [comment] 2019-01-05 17:55
can do one more relog the the test app the one that show this


`{"sections":[{"title":"Live","tiles":[{"title":"Go to Live","subtitle":"","image_ratio":"4by3","image_url":"https://fgl27.github.io/smarttv-twitch/release/githubio/images/smart_live.png","action_data":"{\"screenIdx\":1}","is_playable":false}]},{"title":" Add User","tiles":[{"title":"Go to  Add User","subtitle":"Add a Twitch user to display it's Followed Channels content here","image_ratio":"4by3","image_url":"https://fgl27.github.io/smarttv-twitch/release/githubio/images/smart_add_user.png","action_data":"{\"screenIdx\":2}","is_playable":false}]},{"title":"Featured","tiles":[{"title":"Go to Featured","subtitle":"","image_ratio":"4by3","image_url":"https://fgl27.github.io/smarttv-twitch/release/githubio/images/smart_featured.png","action_data":"{\"screenIdx\":22}","is_playable":false}]},{"title":"Games","tiles":[{"title":"Go to Games","subtitle":"","image_ratio":"4by3","image_url":"https://fgl27.github.io/smarttv-twitch/release/githubio/images/smart_games.png","action_data":"{\"screenIdx\":3}","is_playable":false}]},{"title":"Videos","tiles":[{"title":"Go to Videos","subtitle":"","image_ratio":"4by3","image_url":"https://fgl27.github.io/smarttv-twitch/release/githubio/images/smart_videos.png","action_data":"{\"screenIdx\":18}","is_playable":false}]},{"title":" Clips","tiles":[{"title":"Go to  Clips","subtitle":"","image_ratio":"4by3","image_url":"https://fgl27.github.io/smarttv-twitch/release/githubio/images/smart_cips.png","action_data":"{\"screenIdx\":19}","is_playable":false}]}]} `

but now past the content of the log inside of txt file and attach it here.

thanks

**Comment by Rossano95** [comment] 2019-01-05 18:05
Here it is
[log.txt](https://github.com/fgl27/smarttv-twitch/files/2729737/log.txt)

**Comment by fgl27** [comment] 2019-01-05 18:07
Ok is loging as expected it doesn't work because of something wrong on the OS.

thanks.

**Comment by Rossano95** [comment] 2019-01-12 20:14
Hi, I finded another "issue". It's normal that the subscriptions notifications are not visible in the chat? This is difficult to log. In the Image you can see the difference. On the left it's the app, on the right it's Twitch from the browser. If you want to do some testing for the smart hub you can try the emulator. The behaviour is the same.
![sub](https://user-images.githubusercontent.com/35000827/51078004-fdd18c80-16ae-11e9-87ad-1efd4d73c373.JPG)

**Comment by fgl27** [comment] 2019-01-12 22:56
What the site does, and what twitch provide on they api that can be used on third party app like this is different.

Can you see that notification on the chatlog?
on a site like this https://cbenni.com/ or something like

I don't know if the emulator works well on my machine I try a long time a go and it didn't, but I will try again is a good idea.
Samsung didn't yet replay on the issue.

**Comment by fgl27** [comment] 2019-01-13 00:01
I can emulate TV 5.0 with I think is Tizen 5.0, the error is the same, is as if the app doesn't have access to the API, because trying to get the api version fails.

At least I can test here the day Samsung replay I test here and let you

**Closed** 2019-01-13 05:05 UTC
Labels: bug, help wanted

**Comment by Rossano95** [comment] 2019-01-13 17:34
Ok, thank you

**Comment by Rossano95** [comment] 2019-07-17 22:31
Hello, I have updated the traduction. It needed only a few strings. 

[it_IT.zip](https://github.com/fgl27/smarttv-twitch/files/3404027/it_IT.zip)
