### ISSUE TITLE
Black screen when returning menu

### ISSUE THREAD

**Issue by eze92** [fgl27/smarttv-twitch#60] opened 2019-10-22 12:13 UTC
When you leave a streaming with the back button, there are occasions when the black screen remains bugged even when leaving with the exit button and re-entering persists and the only solution is to wait a couple of minutes until it "picks up" or turn off the tv

**Comment by fgl27** [comment] 2019-10-22 14:03
I can't reproduce it here.

You need to inform what are the exactly steps to reproduce, can you reproduce at any time?

Must be a very precise sequence that you do, open a screen > another > go here > then there > open a stream exit then bug... I need the exactly steps

If you can tell me a exactly why to reproduce I replicate and fix here, if not you will need to follow this steps

https://github.com/fgl27/smarttv-twitch/issues/5#issuecomment-466170992

to install the app in debug mode, and with the debug window open replicate exactly what you are doing and cause the bug, then on the debug console window must show what is cause the app to freeze

Show me the debug window result to see if I can manage to fix.

**Comment by racingsquirrel** [comment] 2019-10-27 22:55
I seem to have this same issue. I currently cannot get out of a stream that I am in. 

Pressing back twice leaves a black screen, I have left this for several minutes and it does not change. Killing the app by holding back does work but on re-entering the app I get "The app was closed while playing, restoring playback".

Pressing up brings up live channels but selecting one of these does nothing and then the UI is unresponsive until force closing and re-entering the app.

Selecting Game Content, Channel Content and Search all lead to black screen.

As I currently can't get out of this stream I cannot attempt to find recreatable steps at this time but will try to do so once this stream ends, as I presume that will allow me out!

**Comment by fgl27** [comment] 2019-10-27 22:58
Same a my previous post, not a thing I can't reproduce, share the logs as I requested.

**Comment by racingsquirrel** [comment] 2019-10-27 23:07
As I stated, I can't attempt to find recreatable steps at this time.

Going forward, it would be useful to have a means to prevent the auto restore of playback after killing the app.

**Comment by fgl27** [comment] 2019-10-27 23:53
have you check settings? for prevent auto playback?

**Comment by fgl27** [comment] 2019-10-28 00:05
Maybe the above, or some other change that I have already push fixed the issue.

If not try to reproduce during a log section.

**Closed** 2019-10-28 05:05 UTC
Labels: bug

**Comment by PerplexedGit** [comment] 2019-10-28 05:07
I am able to reproduce this only when going into a stream from User Menu -> Games -> Select a Game -> A Stream. Note: No authentication key for user. 

Only way to get out is when the stream ends and not following the hosted channel.
